export const courseInfo = [
    {
        id: "walker",
        courseName: "WALKER COURSE (인원 5~6명)",
        course: [
            "Group class 40분, 2회 (cheating, 게임, 레벨인식)",
            "Zoom Group Class 1회",
            "Chat Class 1회",
            "Outing Class (비용별도)",
        ],
        courseUrl: [
            "http://cheereng.com/2#group",
            "http://cheereng.com/2#zoom",
            "http://cheereng.com/2#chatting",
            "http://cheereng.com/2#outing",
        ],
        theme: "yellow",
        bgColor: "#ffffff",
        badge: false,
    },
    {
        id: "runner",
        courseName: "RUNNER COURSE (인원 5~6명)",
        course: [
            "Zoom Group Class 1회",
            "Chatting Class 4회",
            "1: 1 외국인 회화 Class 주 2회 25분",
            "Acquaintance Meeting 1회",
            "언어교환 모임 1회",
        ],
        courseUrl: [
            "http://cheereng.com/2#zoom",
            "http://cheereng.com/2#chatting",
            "",
            "http://cheereng.com/2#outing",
            "http://cheereng.com/2#group",
        ],
        theme: "green",
        bgColor: "#dfdfdf",
        badge: false,
    },
    {
        id: "jumper",
        courseName: "JUMPER COURSE",
        course: [
            "Zoom Group Class 1회",
            "Chatting Class 4회",
            "1: 1 외국인 회화 Class 주 2회 25분",
            "Acquaintance Meeting 1회",
            "언어교환 모임 1회",
        ],
        courseUrl: [
            "http://cheereng.com/2#zoom",
            "http://cheereng.com/2#chatting",
            "",
            "http://cheereng.com/2#outing",
            "http://cheereng.com/2#group",
        ],
        theme: "red",
        bgColor: "#ffffff",
        badge: true,
    },
];
