export const courseInfo = [
    {
        id: "walker",
        courseName: "WALKER COURSE (인원 5~6명)",
        course: [
            "Group Class 40분 월 2회",
            "Zoom Class 월 1회",
            "Chatting Class 주 1회",
            "Outing Class 월 1회 (비용 별도)",
        ],
        courseUrl: [
            "http://cheereng.com/2#group",
            "http://cheereng.com/2#zoom",
            "http://cheereng.com/2#chatting",
            "http://cheereng.com/2#outing",
        ],
        theme: "yellow",
        bgColor: "#ffffff",
        badge: false,
        text: "* Group Class는 수,금,토 중 요일 한 개 선택",
    },
    {
        id: "runner",
        courseName: "RUNNER COURSE (인원 5~6명)",
        course: [
            "1 : 1 외국인 회화 Class 주2회 25분",
            "Chatting Class 주 1회",
            "Networking 모임 월 2회",
            "Outing Class 월 1회 (비용 별도)",
        ],
        courseUrl: [
            "http://cheereng.com/2#zoom",
            "http://cheereng.com/2#chatting",
            "",
            "http://cheereng.com/2#outing",
            "http://cheereng.com/2#group",
        ],
        theme: "green",
        bgColor: "#dfdfdf",
        badge: false,
        text: "",
    },
    {
        id: "jumper",
        courseName: "JUMPER COURSE",
        course: ["치어 관리가 들어간 1대1 외국인 회화 Class"],
        courseUrl: [
            "http://cheereng.com/2#zoom",
            "http://cheereng.com/2#chatting",
            "",
            "http://cheereng.com/2#outing",
            "http://cheereng.com/2#group",
        ],
        theme: "red",
        bgColor: "#ffffff",
        badge: true,
        text: "",
    },
];
